//! Identifier types shared across the kernel.
//!
//! These are deliberately newtypes around primitive integers so that a
//! `RequestId` cannot be accidentally used in place of a `BackendId`.
//!
//! The text representation is hexadecimal so that operators reading a log
//! line can correlate by visual scan: a request id and a backend id always
//! look obviously different in length and prefix.

use core::fmt;
use core::sync::atomic::{AtomicU64, Ordering};

/// Per-request identifier.
///
/// Generated by the accept loop using a process-local monotonically increasing
/// counter. Not globally unique across processes; pair with the host's MAC or
/// a UUID prefix if global uniqueness is needed (none of the v0.1 surfaces
/// require it).
///
/// Format in logs: `req-<lowercase hex>`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct RequestId(pub u64);

impl RequestId {
    /// Allocate a new request id from the process-local counter.
    ///
    /// O(1). Wraps after `u64::MAX` requests, which is comfortably more than
    /// any single Riftgate process will ever serve.
    #[inline]
    pub fn next() -> Self {
        static COUNTER: AtomicU64 = AtomicU64::new(1);
        Self(COUNTER.fetch_add(1, Ordering::Relaxed))
    }
}

impl fmt::Debug for RequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "req-{:x}", self.0)
    }
}

impl fmt::Display for RequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "req-{:x}", self.0)
    }
}

/// Per-tenant identifier.
///
/// Used by the rate limiter (`v0.2`+) and the MCP capability broker (`v0.5`+)
/// to scope per-tenant policy. In `v0.1` the gateway is single-tenant by
/// default; this type exists so the trait surface is forward-compatible.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct TenantId(pub u32);

impl fmt::Debug for TenantId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "tenant-{}", self.0)
    }
}

impl fmt::Display for TenantId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "tenant-{}", self.0)
    }
}

/// Per-route identifier.
///
/// Routes are loaded from configuration and assigned ids in the order they
/// appear. Used by the rate limiter and the router to scope per-route policy.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct RouteId(pub u32);

impl fmt::Debug for RouteId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "route-{}", self.0)
    }
}

impl fmt::Display for RouteId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "route-{}", self.0)
    }
}

/// Per-shard identifier.
///
/// Each Tokio worker thread owns a logical shard. Per [ADR
/// 0004](../../../docs/06-adrs/0004-per-shard-default-stealing-opt-in.md) we
/// have M logical shards on N Tokio threads with no pinning in `v0.1`.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct ShardId(pub u16);

impl fmt::Debug for ShardId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "shard-{}", self.0)
    }
}

impl fmt::Display for ShardId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "shard-{}", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_id_format_is_stable() {
        let id = RequestId(0xdead_beef);
        assert_eq!(format!("{id}"), "req-deadbeef");
        assert_eq!(format!("{id:?}"), "req-deadbeef");
    }

    #[test]
    fn request_id_next_is_monotonic() {
        let a = RequestId::next();
        let b = RequestId::next();
        assert!(
            b.0 > a.0,
            "request ids must be monotonic, got {a:?} then {b:?}"
        );
    }

    #[test]
    fn tenant_route_shard_format_is_stable() {
        assert_eq!(format!("{}", TenantId(7)), "tenant-7");
        assert_eq!(format!("{}", RouteId(42)), "route-42");
        assert_eq!(format!("{}", ShardId(3)), "shard-3");
    }
}
